Repository poneciak57/ProjectKomis, pull requests merged in 2022-04, with the labels that each got.

#4 Logout
  PHP/EndPoints/logout.EP.php
Labels: enhancement, feature

#3 Login system
  PHP/Classes/login.class.php
  PHP/Classes/login.controller.php
  PHP/EndPoints/login.EP.php
  PHP/EndPoints/logout.EP.php
  PHP/EndPoints/signup.EP.php
  PHP/Structs/user.struct.php
Labels: bug, enhancement, feature

#5 Inactivity/logout
  PHP/Classes/login.controller.php
  PHP/Embeds/logout-check.embed.php
Labels: bug, enhancement, feature

#6 Login_patch
  PHP/Classes/login.class.php
  PHP/Classes/login.controller.php
  PHP/Classes/signup.class.php
  PHP/Classes/signup.controller.php
  PHP/Embeds/logout-check.embed.php
  PHP/EndPoints/check-login.EP.php
  PHP/EndPoints/login.EP.php
  PHP/EndPoints/logout.EP.php
  PHP/EndPoints/signup.EP.php
  Pages/login.page.php
  Pages/signup.page.php
  index.php
Labels: bug, enhancement

#7 Refactor
  PHP/Classes/DBh.class.php
  PHP/Classes/Structs/user.struct.php
  PHP/Classes/login.class.php
  PHP/Classes/login.controller.php
  PHP/Classes/signup.class.php
  PHP/Classes/signup.controller.php
  PHP/EndPoints/Data/check-login.EP.php
  PHP/EndPoints/Login&Signup/login.EP.php
  PHP/EndPoints/Login&Signup/logout.EP.php
  PHP/EndPoints/Login&Signup/signup.EP.php
  PHP/EndPoints/check-login.EP.php
Labels: refactor

#9 Offers and site structure
  JS/offers.display.js
  PHP/Classes/DBh.class.php
  PHP/Classes/Structs/user.struct.php
  PHP/Classes/login.class.php
  PHP/Classes/login.controller.php
  PHP/Classes/offers.class.php
  PHP/Classes/offers.controller.php
  PHP/Classes/pageviews.class.php
  PHP/Classes/signup.class.php
  PHP/Classes/signup.controller.php
  PHP/Classes/statistics.class.php
  PHP/Embeds/add-view.embed.php
  PHP/Embeds/logout-check.embed.php
  PHP/EndPoints/Data/check-login.EP.php
  PHP/EndPoints/Data/offer-delete.EP.php
  PHP/EndPoints/Data/offers-single.EP.php
  PHP/EndPoints/Data/offers-stack.EP.php
  PHP/EndPoints/Login&Signup/login.EP.php
  PHP/EndPoints/Login&Signup/logout.EP.php
  Pages/error.page.php
  Pages/home.page.php
  Pages/login.page.php
  Pages/offers.page.php
  index.php
Labels: bug, enhancement, feature, refactor

#13 Finished main html and css of offers
  .gitignore
  Css/car-offer.module.styles.css
  Css/footer.module.styles.css
  Css/navbar.module.styles.css
  Css/offers.page.styles.css
  Css/variables.styles.css
  Modules/car-offer.module.php
  Pages/offers.page.php
  Sources/arrow-icon.svg
  Sources/filter-icon.svg
  Sources/heart-icon-red.svg
  Sources/search-icon.svg
Labels: bug, enhancement, feature

#15 Simple single offer EP
  PHP/Classes/offers.class.php
  PHP/Classes/offers.controller.php
Labels: enhancement, feature

#16 JS changing pages
  Css/offers.page.styles.css
  Css/variables.styles.css
  JS/offers.display.js
  Pages/offers.page.php
  Sources/double-arrow-icon.svg
Labels: bug, enhancement, feature
